//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace AutoPBR.App.Lang;

using System.Globalization;
using System.Resources;

/// <summary>Strongly-typed access to Lang resources. Set Culture to switch language at runtime.</summary>
public static class Resources
{
    private static ResourceManager? _resourceMan;
    private static CultureInfo? _resourceCulture;

    public static CultureInfo? Culture
    {
        get => _resourceCulture;
        set => _resourceCulture = value;
    }

    public static string ColorScheme => GetString("ColorScheme");
    public static string ColorSchemeDark => GetString("ColorSchemeDark");
    public static string ColorSchemeBlue => GetString("ColorSchemeBlue");
    public static string ColorSchemeGreen => GetString("ColorSchemeGreen");
    public static string ColorSchemePurple => GetString("ColorSchemePurple");
    public static string ColorSchemeAmber => GetString("ColorSchemeAmber");
    public static string ColorSchemeTeal => GetString("ColorSchemeTeal");
    public static string ColorSchemeRose => GetString("ColorSchemeRose");
    public static string ColorSchemeMono => GetString("ColorSchemeMono");
    public static string ColorSchemeOcean => GetString("ColorSchemeOcean");
    public static string ColorSchemeSunset => GetString("ColorSchemeSunset");
    public static string Language => GetString("Language");
    public static string Appearance => GetString("Appearance");
    public static string AppTitle => GetString("AppTitle");
    public static string AppSubtitle => GetString("AppSubtitle");
    public static string TabConvert => GetString("TabConvert");
    public static string TabScan => GetString("TabScan");
    public static string TabExplore => GetString("TabExplore");
    public static string ScanButton => GetString("ScanButton");
    public static string ExploreArchiveContents => GetString("ExploreArchiveContents");
    public static string ResourceExplorer => GetString("ResourceExplorer");
    public static string ExploreEmptyMessage => GetString("ExploreEmptyMessage");
    public static string ExploreExpandAll => GetString("ExploreExpandAll");
    public static string ExploreCollapseAll => GetString("ExploreCollapseAll");
    public static string ExploreBack => GetString("ExploreBack");
    public static string ExploreFocusAssets => GetString("ExploreFocusAssets");
    public static string TabTune => GetString("TabTune");
    public static string TabSettings => GetString("TabSettings");
    public static string Input => GetString("Input");
    public static string ResourcePackWatermark => GetString("ResourcePackWatermark");
    public static string Browse => GetString("Browse");
    public static string Log => GetString("Log");
    public static string GenerationSettings => GetString("GenerationSettings");
    public static string TuneNormals => GetString("TuneNormals");
    public static string TuneSpecular => GetString("TuneSpecular");
    public static string TuneHeight => GetString("TuneHeight");
    public static string NormalStrength => GetString("NormalStrength");
    public static string NormalStrengthTooltip => GetString("NormalStrengthTooltip");
    public static string HeightStrength => GetString("HeightStrength");
    public static string HeightStrengthTooltip => GetString("HeightStrengthTooltip");
    public static string Derivative => GetString("Derivative");
    public static string SmoothnessScale => GetString("SmoothnessScale");
    public static string SmoothnessScaleTooltip => GetString("SmoothnessScaleTooltip");
    public static string MetallicBoost => GetString("MetallicBoost");
    public static string MetallicBoostTooltip => GetString("MetallicBoostTooltip");
    public static string PorosityBias => GetString("PorosityBias");
    public static string PorosityBiasTooltip => GetString("PorosityBiasTooltip");
    public static string FastSpecular => GetString("FastSpecular");
    public static string FastSpecularTooltip => GetString("FastSpecularTooltip");
    public static string Foliage => GetString("Foliage");
    public static string FoliageTooltip => GetString("FoliageTooltip");
    public static string IgnoreAll => GetString("IgnoreAll");
    public static string NoHeight => GetString("NoHeight");
    public static string ConvertAll => GetString("ConvertAll");
    public static string HeightFromNormals => GetString("HeightFromNormals");
    public static string HeightFromNormalsTooltip => GetString("HeightFromNormalsTooltip");
    public static string NormalsFromDeepBump => GetString("NormalsFromDeepBump");
    public static string NormalsFromDeepBumpTooltip => GetString("NormalsFromDeepBumpTooltip");
    public static string DeepBumpOverlap => GetString("DeepBumpOverlap");
    public static string DeepBumpOverlapTooltip => GetString("DeepBumpOverlapTooltip");
    public static string DeepBumpOverlapSmall => GetString("DeepBumpOverlapSmall");
    public static string DeepBumpOverlapMedium => GetString("DeepBumpOverlapMedium");
    public static string DeepBumpOverlapLarge => GetString("DeepBumpOverlapLarge");
    public static string TextureTypes => GetString("TextureTypes");
    public static string Blocks => GetString("Blocks");
    public static string BlocksTooltip => GetString("BlocksTooltip");
    public static string Items => GetString("Items");
    public static string ItemsTooltip => GetString("ItemsTooltip");
    public static string Armor => GetString("Armor");
    public static string ArmorTooltip => GetString("ArmorTooltip");
    public static string Entity => GetString("Entity");
    public static string EntityTooltip => GetString("EntityTooltip");
    public static string Particles => GetString("Particles");
    public static string ParticlesTooltip => GetString("ParticlesTooltip");
    public static string FilterWatermark => GetString("FilterWatermark");
    public static string Output => GetString("Output");
    public static string OutputFolderWatermark => GetString("OutputFolderWatermark");
    public static string OutputPathWatermark => GetString("OutputPathWatermark");
    public static string Engine => GetString("Engine");
    public static string MaxThreads => GetString("MaxThreads");
    public static string MaxThreadsTooltip => GetString("MaxThreadsTooltip");
    public static string TempFolder => GetString("TempFolder");
    public static string TempFolderTooltip => GetString("TempFolderTooltip");
    public static string TempFolderWatermark => GetString("TempFolderWatermark");
    public static string CustomThreadedExtraction => GetString("CustomThreadedExtraction");
    public static string CustomThreadedExtractionTooltip => GetString("CustomThreadedExtractionTooltip");
    public static string UseLegacyExtractor => GetString("UseLegacyExtractor");
    public static string UseLegacyExtractorTooltip => GetString("UseLegacyExtractorTooltip");
    public static string Cancel => GetString("Cancel");
    public static string Convert => GetString("Convert");
    public static string UIThemeTooltip => GetString("UIThemeTooltip");
    public static string UILanguageTooltip => GetString("UILanguageTooltip");

    public static string GetStatusString(string key, params object[] args)
    {
        var s = GetString(key);
        return args.Length > 0 ? string.Format(s, args) : s;
    }

    public static string GetString(string key)
    {
        var rm = ResourceManager;
        var c = _resourceCulture;
        return rm?.GetString(key, c) ?? key;
    }

    private static ResourceManager ResourceManager
    {
        get
        {
            if (_resourceMan is null)
            {
                var t = typeof(Resources);
                _resourceMan = new ResourceManager("AutoPBR.App.Lang.Resources", t.Assembly);
            }
            return _resourceMan;
        }
    }
}
