namespace AutoPBR.App.Rendering.OpenGL;

public sealed partial class OpenGlPreviewBackend
{
    private readonly record struct TaaResolveUniformLocs(
        int Current,
        int History,
        int SceneDepth,
        int TaaSignal,
        int HasSceneDepth,
        int HasTaaSignal,
        int HasHistory,
        int InvViewProj,
        int PrevViewProj,
        int TexelSize,
        int CaptureTexelSize,
        int CurrentJitterPixels,
        int TemporalWeight,
        int StableTemporalBoost,
        int MaxStableTemporal,
        int TaaSharpenStrength,
        int DepthEdgeHistoryFloor,
        int EdgeAaBlend,
        int SourceFilterStrength,
        int SilhouetteHistoryWeight,
        int FxaaEdgeStrength,
        int FxaaLumaEdgeStrength,
        int FxaaLumaThreshold,
        int ForceFxaa,
        int HdrPresent);

    private readonly record struct ScenePresentUniformLocs(
        int SceneColor,
        int HdrPresent,
        int SceneIsLinear,
        int HdrPaperWhiteNits,
        int HdrPeakNits);

    private readonly record struct SsaoUniformLocs(
        int SceneDepth,
        int ViewNormal,
        int InvProj,
        int Proj,
        int AoTexelSize,
        int AoRadius,
        int AoBias,
        int AoPower,
        int AoIntensity,
        int AoSampleCount,
        int FrameIndex,
        int HasSceneDepth,
        int HasViewNormal);

    private readonly record struct GtaoUniformLocs(
        int SceneDepth,
        int ViewNormal,
        int InvProj,
        int Proj,
        int AoTexelSize,
        int AoRadius,
        int AoBias,
        int AoPower,
        int AoIntensity,
        int GtaoSlices,
        int GtaoSteps,
        int FrameIndex,
        int HasSceneDepth,
        int HasViewNormal,
        int EnableMultiBounce);

    private readonly record struct AoBilateralUniformLocs(
        int AoSource,
        int SceneDepth,
        int AoTexelSize,
        int BlurDirection,
        int DepthSigma,
        int HasSceneDepth);

    private readonly record struct AoTemporalUniformLocs(
        int AoCurrent,
        int AoHistory,
        int SceneDepth,
        int InvViewProj,
        int PrevViewProj,
        int CameraPos,
        int TemporalWeight,
        int HasHistory,
        int HasSceneDepth);

    private readonly record struct AoCompositeUniformLocs(
        int SceneColor,
        int Ao,
        int ViewNormal,
        int HdrPresent,
        int SceneIsLinear,
        int HdrPaperWhiteNits,
        int HdrPeakNits,
        int AoStrength,
        int HasAo,
        int HasViewNormal,
        int AoDebugView);

    private readonly record struct ScreenSpaceGodRayUniformLocs(
        int SceneDepth,
        int CloudOpacity,
        int SunUv,
        int SunDiscRadius,
        int SunConeRadius,
        int Aspect,
        int Strength,
        int ScatterTint,
        int SkyWashFloor,
        int TerrainShaftScale,
        int EnergyKnee,
        int HasCloudOpacity,
        int HdrPresent,
        int HdrPaperWhiteNits,
        int HdrPeakNits);

    private readonly record struct ShadowAwareGodRayUniformLocs(
        int SceneDepth,
        int ShadowMap,
        int ShadowMapNear,
        int ShadowMapMid,
        int InvViewProj,
        int LightViewProj,
        int LightViewProjNear,
        int LightViewProjMid,
        int CameraPos,
        int SunUv,
        int SunDiscRadius,
        int SunConeRadius,
        int Aspect,
        int Strength,
        int HdrPresent,
        int HdrPaperWhiteNits,
        int HdrPeakNits,
        int LayerHeight,
        int VolumeHeight,
        int CloudDensity,
        int VolumeSize,
        int GroundWorldY,
        int FogSlabHeight,
        int HeightFogStrength,
        int ShadowTexelSize,
        int ShadowTexelSizeNear,
        int ShadowTexelSizeMid,
        int ShadowMinBias,
        int EnableShadowMap,
        int EnableShadowCascades,
        int CascadeSplitDistance,
        int CascadeMidSplitDistance,
        int CascadeBlendWidth,
        int ShadowDistance,
        int ShadowFadeStart,
        int EnableCloudAttenuation);

    private readonly record struct GodRayUpsampleUniformLocs(
        int HalfResRays,
        int SceneDepth,
        int History,
        int InvViewProj,
        int PrevViewProj,
        int HalfResTexelSize,
        int TemporalWeight,
        int HasHistory);

    private readonly record struct GodRayCanopyRefineUniformLocs(
        int Rays,
        int FoliageMask,
        int Strength);

    private readonly record struct GodRayCompositeUniformLocs(
        int Rays,
        int HasCloudMask,
        int CloudMask,
        int CloudPresent,
        int HdrPresent,
        int HdrPaperWhiteNits,
        int HdrPeakNits,
        int TransmittanceComposite);

    private readonly record struct VolumeInjectUniformLocs(
        int CameraPos,
        int CamRight,
        int CamUp,
        int CamForward,
        int LightDir,
        int LightColor,
        int HalfExtent,
        int SliceCount,
        int DepthDistribution,
        int LayerHeight,
        int VolumeHeight,
        int CloudDensity,
        int VolumeSize,
        int GroundWorldY,
        int FogSlabHeight,
        int HeightFogStrength,
        int DebugDensity,
        int LightViewProj,
        int LightViewProjNear,
        int LightViewProjMid,
        int ShadowTexelSize,
        int ShadowTexelSizeNear,
        int ShadowTexelSizeMid,
        int ShadowMinBias,
        int EnableShadowMap,
        int EnableShadowCascades,
        int CascadeSplitDistance,
        int CascadeMidSplitDistance,
        int CascadeBlendWidth,
        int ShadowDistance,
        int ShadowFadeStart,
        int ShadowMap,
        int ShadowMapNear,
        int ShadowMapMid,
        int SliceIndex,
        int CloudGroundTransmittance,
        int HasCloudGroundTransmittance,
        int CloudGroundBasisRight,
        int CloudGroundBasisUp,
        int CloudGroundPlaneCenter,
        int CloudGroundWorldSpan,
        int CloudGroundTexelSize);

    private readonly record struct VolumeInjectComputeUniformLocs(
        int CameraPos,
        int CamRight,
        int CamUp,
        int CamForward,
        int LightDir,
        int LightColor,
        int HalfExtent,
        int FroxelSize,
        int SliceCount,
        int DepthDistribution,
        int LayerHeight,
        int VolumeHeight,
        int CloudDensity,
        int VolumeSize,
        int GroundWorldY,
        int FogSlabHeight,
        int HeightFogStrength,
        int DebugDensity,
        int LightViewProj,
        int LightViewProjNear,
        int LightViewProjMid,
        int ShadowTexelSize,
        int ShadowTexelSizeNear,
        int ShadowTexelSizeMid,
        int ShadowMinBias,
        int EnableShadowMap,
        int EnableShadowCascades,
        int CascadeSplitDistance,
        int CascadeMidSplitDistance,
        int CascadeBlendWidth,
        int ShadowDistance,
        int ShadowFadeStart,
        int ShadowMap,
        int ShadowMapNear,
        int ShadowMapMid,
        int CloudGroundTransmittance,
        int HasCloudGroundTransmittance,
        int CloudGroundBasisRight,
        int CloudGroundBasisUp,
        int CloudGroundPlaneCenter,
        int CloudGroundWorldSpan,
        int CloudGroundTexelSize);

    private readonly record struct VolumeIntegrateUniformLocs(
        int FroxelVolume,
        int FroxelOccupancy,
        int SceneDepth,
        int InvViewProj,
        int CameraPos,
        int CamRight,
        int CamUp,
        int CamForward,
        int LightDir,
        int LightColor,
        int HalfExtent,
        int SliceCount,
        int FroxelTexelSize,
        int Strength,
        int Jitter,
        int ScatterGain,
        int Extinction,
        int AmbientFillGain,
        int PhaseDirectivity,
        int DepthDistribution,
        int PrevIntegrate,
        int HasPrevIntegrate,
        int PrevFroxelVolume,
        int HasPrevFroxel,
        int PrevViewProj,
        int PrevCameraPos,
        int PrevCamRight,
        int PrevCamUp,
        int PrevCamForward,
        int PrevHalfExtent,
        int TemporalWeight,
        int FroxelTemporalWeight,
        int CloudTransmittance,
        int CloudData,
        int HasCloudTransmittance,
        int CloudDataDirect);

    private readonly record struct CloudUniformLocs(
        int CloudNoise,
        int CoverageMap,
        int SkyViewLut,
        int DetailNoise,
        int CloudStbn,
        int SceneDepth,
        int InvViewProj,
        int CameraPos,
        int GroundWorldY,
        int PlanetRadius,
        int SunDir,
        int SunIntensity,
        int LayerHeight,
        int VolumeHeight,
        int Density,
        int CoverageScale,
        int VolumeSize,
        int PixelAngularSize,
        int WindOffset,
        int CirrusStrength,
        int CirrusWindOffset,
        int CirrusWindDir,
        int Quality,
        int MarchSteps,
        int DebugView,
        int HasSceneDepth,
        int FramePhase,
        int CloudFrameIndex,
        int HasCloudNoise,
        int HasDetailNoise,
        int HasCloudStbn,
        int HasCoverageMap,
        int HasSkyLut,
        int CloudDataDirect,
        int DensityAssetVersion,
        int DensityAssetProfileCode,
        int SparseCloudAtlas,
        int SparseCloudPageL0,
        int SparseCloudPageL1,
        int SparseCloudPageL2,
        int SparseCloudOriginL0,
        int SparseCloudOriginL1,
        int SparseCloudOriginL2,
        int HasSparseCloudTraversal,
        int CloudLightNear,
        int CloudLightFar,
        int CloudLightBasisRight,
        int CloudLightBasisUp,
        int CloudLightBasisForward,
        int CloudLightNearPlaneCenter,
        int CloudLightFarPlaneCenter,
        int CloudLightNearWorldSpan,
        int CloudLightFarWorldSpan,
        int CloudLightNearDepthMin,
        int CloudLightFarDepthMin,
        int CloudLightNearDepthSpan,
        int CloudLightFarDepthSpan,
        int CloudLightNearDepth,
        int CloudLightFarDepth,
        int CloudLightNearOverlap,
        int HasCloudLightNear,
        int HasCloudLightFar,
        int CloudScatterOctave1,
        int CloudScatterOctave2,
        int CloudScatterEnergyClamp,
        int CloudCachedSkyVisibilityFloor,
        int CloudGroundBounceColor,
        int CloudGroundBounceStrength,
        int CloudLocalConeTapCount,
        int CloudLocalConeRange,
        int CloudLocalConeOpticalDepthScale,
        int CumulusLayerCount,
        int InterDeckGap,
        int HeightVariance,
        int UpperThicknessScale,
        int UpperCoverageScale,
        int UpperDensityScale,
        int UpperWindOffset,
        int CirrusGap,
        int CirrusThickness,
        int StyleBias);

    private readonly record struct CloudTemporalUniformLocs(
        int CurrentClouds,
        int CurrentCloudData,
        int HistoryClouds,
        int HistoryCloudData,
        int HistoryCloudMoments,
        int InvViewProj,
        int PrevViewProj,
        int CameraPos,
        int PrevCameraPos,
        int WindDelta,
        int CirrusWindDelta,
        int TexelSize,
        int TemporalWeight,
        int MomentSigma,
        int MomentMinBand,
        int HistoryConfidence,
        int TemporalStability,
        int HasHistory,
        int HasMoments,
        int CloudDataDirect);

    private readonly record struct CloudUpsampleUniformLocs(
        int Clouds,
        int CloudData,
        int CloudTexelSize,
        int HasSceneDepth,
        int SceneDepth,
        int InvViewProj,
        int CameraPos,
        int SunDir,
        int SunCosDiscEdge,
        int SunDiscVisibility,
        int CloudDataDirect,
        int CloudExposure,
        int HdrPresent,
        int HdrPaperWhiteNits,
        int HdrPeakNits,
        int ApplyCloudEncoding,
        int CloudSourceFullResolution);

    private readonly record struct CloudRepairUniformLocs(
        int Clouds,
        int CloudData,
        int SceneDepth,
        int CloudNoise,
        int DetailNoise,
        int CloudStbn,
        int CoverageMap,
        int SkyViewLut,
        int CloudTexelSize,
        int InvViewProj,
        int CameraPos,
        int SunDir,
        int SunIntensity,
        int GroundWorldY,
        int PlanetRadius,
        int LayerHeight,
        int VolumeHeight,
        int Density,
        int CoverageScale,
        int VolumeSize,
        int PixelAngularSize,
        int WindOffset,
        int CirrusStrength,
        int CirrusWindOffset,
        int CirrusWindDir,
        int MarchSteps,
        int HasSceneDepth,
        int HasCloudNoise,
        int HasDetailNoise,
        int HasCloudStbn,
        int HasCoverageMap,
        int HasSkyLut,
        int SourceCloudDataDirect,
        int DensityAssetVersion,
        int CloudFrameIndex,
        int RepairStability,
        int SparseCloudAtlas,
        int SparseCloudPageL0,
        int SparseCloudPageL1,
        int SparseCloudPageL2,
        int SparseCloudOriginL0,
        int SparseCloudOriginL1,
        int SparseCloudOriginL2,
        int HasSparseCloudTraversal,
        int CumulusLayerCount,
        int InterDeckGap,
        int HeightVariance,
        int UpperThicknessScale,
        int UpperCoverageScale,
        int UpperDensityScale,
        int UpperWindOffset,
        int CirrusGap,
        int CirrusThickness,
        int StyleBias);

    private readonly record struct CloudCompositeUniformLocs(
        int Rays,
        int CloudPresent,
        int CloudExposure,
        int HdrPresent,
        int HdrPaperWhiteNits,
        int HdrPeakNits,
        int ApplyCloudEncoding);

    private readonly record struct AtmoTransUniformLocs(
        int Turbidity,
        int HorizonFalloff);

    private readonly record struct AtmoSkyViewUniformLocs(
        int TransmittanceLut,
        int SunDir,
        int Turbidity,
        int SunIntensity,
        int HorizonFalloff);

    private readonly record struct AtmoSkyUniformLocs(
        int SkyViewLut,
        int Turbidity,
        int HorizonFalloff,
        int InvViewProj,
        int CameraPos,
        int LightDir,
        int SunIntensity,
        int HorizonFogStrength,
        int GroundWorldY,
        int SkyExposure,
        int SunDiscStrength,
        int SunDiscBrightness,
        int SunCosDiscEdge,
        int MoonCosDiscEdge,
        int RenderTime,
        int ViewportAspect,
        int SunDiscRadiusUv,
        int HdrPresent);

    private readonly record struct ProceduralSkyUniformLocs(
        int InvViewProj,
        int CameraPos,
        int LightDir,
        int SunIntensity,
        int SkyExposure,
        int RenderTime,
        int Turbidity,
        int HorizonFalloff,
        int HorizonFogStrength,
        int GroundWorldY,
        int SunDiscStrength,
        int SunDiscBrightness,
        int SunCosDiscEdge,
        int MoonCosDiscEdge,
        int ViewportAspect,
        int SunDiscRadiusUv,
        int SunElevation,
        int HdrPresent);

    private TaaResolveUniformLocs _taaResolveUniformLocs;
    private ScenePresentUniformLocs _scenePresentUniformLocs;
    private SsaoUniformLocs _ssaoUniformLocs;
    private GtaoUniformLocs _gtaoUniformLocs;
    private AoBilateralUniformLocs _aoBilateralUniformLocs;
    private AoTemporalUniformLocs _aoTemporalUniformLocs;
    private AoCompositeUniformLocs _aoCompositeUniformLocs;
    private ScreenSpaceGodRayUniformLocs _screenSpaceGodRayUniformLocs;
    private ShadowAwareGodRayUniformLocs _shadowAwareGodRayUniformLocs;
    private GodRayUpsampleUniformLocs _godRayUpsampleUniformLocs;
    private GodRayCanopyRefineUniformLocs _godRayCanopyRefineUniformLocs;
    private GodRayCompositeUniformLocs _godRayCompositeUniformLocs;
    private VolumeInjectUniformLocs _volumeInjectUniformLocs;
    private VolumeInjectComputeUniformLocs _volumeInjectComputeUniformLocs;
    private VolumeIntegrateUniformLocs _volumeIntegrateUniformLocs;
    private CloudUniformLocs _cloudUniformLocs;
    private CloudTemporalUniformLocs _cloudTemporalUniformLocs;
    private CloudUpsampleUniformLocs _cloudUpsampleUniformLocs;
    private CloudRepairUniformLocs _cloudRepairUniformLocs;
    private CloudCompositeUniformLocs _cloudCompositeUniformLocs;
    private AtmoTransUniformLocs _atmoTransUniformLocs;
    private AtmoSkyViewUniformLocs _atmoSkyViewUniformLocs;
    private AtmoSkyUniformLocs _atmoSkyUniformLocs;
    private ProceduralSkyUniformLocs _proceduralSkyUniformLocs;

    private static TaaResolveUniformLocs ResolveTaaResolveUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uCurrent"),
            program.GetUniformLocation("uHistory"),
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uTaaSignal"),
            program.GetUniformLocation("uHasSceneDepth"),
            program.GetUniformLocation("uHasTaaSignal"),
            program.GetUniformLocation("uHasHistory"),
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uPrevViewProj"),
            program.GetUniformLocation("uTexelSize"),
            program.GetUniformLocation("uCaptureTexelSize"),
            program.GetUniformLocation("uCurrentJitterPixels"),
            program.GetUniformLocation("uTemporalWeight"),
            program.GetUniformLocation("uStableTemporalBoost"),
            program.GetUniformLocation("uMaxStableTemporal"),
            program.GetUniformLocation("uTaaSharpenStrength"),
            program.GetUniformLocation("uDepthEdgeHistoryFloor"),
            program.GetUniformLocation("uEdgeAaBlend"),
            program.GetUniformLocation("uSourceFilterStrength"),
            program.GetUniformLocation("uSilhouetteHistoryWeight"),
            program.GetUniformLocation("uFxaaEdgeStrength"),
            program.GetUniformLocation("uFxaaLumaEdgeStrength"),
            program.GetUniformLocation("uFxaaLumaThreshold"),
            program.GetUniformLocation("uForceFxaa"),
            program.GetUniformLocation("uHdrPresent"));

    private static ScenePresentUniformLocs ResolveScenePresentUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uSceneColor"),
            program.GetUniformLocation("uHdrPresent"),
            program.GetUniformLocation("uSceneIsLinear"),
            program.GetUniformLocation("uHdrPaperWhiteNits"),
            program.GetUniformLocation("uHdrPeakNits"));

    private static SsaoUniformLocs ResolveSsaoUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uViewNormal"),
            program.GetUniformLocation("uInvProj"),
            program.GetUniformLocation("uProj"),
            program.GetUniformLocation("uAoTexelSize"),
            program.GetUniformLocation("uAoRadius"),
            program.GetUniformLocation("uAoBias"),
            program.GetUniformLocation("uAoPower"),
            program.GetUniformLocation("uAoIntensity"),
            program.GetUniformLocation("uAoSampleCount"),
            program.GetUniformLocation("uFrameIndex"),
            program.GetUniformLocation("uHasSceneDepth"),
            program.GetUniformLocation("uHasViewNormal"));

    private static GtaoUniformLocs ResolveGtaoUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uViewNormal"),
            program.GetUniformLocation("uInvProj"),
            program.GetUniformLocation("uProj"),
            program.GetUniformLocation("uAoTexelSize"),
            program.GetUniformLocation("uAoRadius"),
            program.GetUniformLocation("uAoBias"),
            program.GetUniformLocation("uAoPower"),
            program.GetUniformLocation("uAoIntensity"),
            program.GetUniformLocation("uGtaoSlices"),
            program.GetUniformLocation("uGtaoSteps"),
            program.GetUniformLocation("uFrameIndex"),
            program.GetUniformLocation("uHasSceneDepth"),
            program.GetUniformLocation("uHasViewNormal"),
            program.GetUniformLocation("uEnableMultiBounce"));

    private static AoBilateralUniformLocs ResolveAoBilateralUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uAoSource"),
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uAoTexelSize"),
            program.GetUniformLocation("uBlurDirection"),
            program.GetUniformLocation("uDepthSigma"),
            program.GetUniformLocation("uHasSceneDepth"));

    private static AoTemporalUniformLocs ResolveAoTemporalUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uAoCurrent"),
            program.GetUniformLocation("uAoHistory"),
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uPrevViewProj"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uTemporalWeight"),
            program.GetUniformLocation("uHasHistory"),
            program.GetUniformLocation("uHasSceneDepth"));

    private static AoCompositeUniformLocs ResolveAoCompositeUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uSceneColor"),
            program.GetUniformLocation("uAo"),
            program.GetUniformLocation("uViewNormal"),
            program.GetUniformLocation("uHdrPresent"),
            program.GetUniformLocation("uSceneIsLinear"),
            program.GetUniformLocation("uHdrPaperWhiteNits"),
            program.GetUniformLocation("uHdrPeakNits"),
            program.GetUniformLocation("uAoStrength"),
            program.GetUniformLocation("uHasAo"),
            program.GetUniformLocation("uHasViewNormal"),
            program.GetUniformLocation("uAoDebugView"));

    private static ScreenSpaceGodRayUniformLocs ResolveScreenSpaceGodRayUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uCloudOpacity"),
            program.GetUniformLocation("uSunUv"),
            program.GetUniformLocation("uSunDiscRadius"),
            program.GetUniformLocation("uSunConeRadius"),
            program.GetUniformLocation("uAspect"),
            program.GetUniformLocation("uStrength"),
            program.GetUniformLocation("uScatterTint"),
            program.GetUniformLocation("uSkyWashFloor"),
            program.GetUniformLocation("uTerrainShaftScale"),
            program.GetUniformLocation("uEnergyKnee"),
            program.GetUniformLocation("uHasCloudOpacity"),
            program.GetUniformLocation("uHdrPresent"),
            program.GetUniformLocation("uHdrPaperWhiteNits"),
            program.GetUniformLocation("uHdrPeakNits"));

    private static ShadowAwareGodRayUniformLocs ResolveShadowAwareGodRayUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uShadowMap"),
            program.GetUniformLocation("uShadowMapNear"),
            program.GetUniformLocation("uShadowMapMid"),
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uLightViewProj"),
            program.GetUniformLocation("uLightViewProjNear"),
            program.GetUniformLocation("uLightViewProjMid"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uSunUv"),
            program.GetUniformLocation("uSunDiscRadius"),
            program.GetUniformLocation("uSunConeRadius"),
            program.GetUniformLocation("uAspect"),
            program.GetUniformLocation("uStrength"),
            program.GetUniformLocation("uHdrPresent"),
            program.GetUniformLocation("uHdrPaperWhiteNits"),
            program.GetUniformLocation("uHdrPeakNits"),
            program.GetUniformLocation("uLayerHeight"),
            program.GetUniformLocation("uVolumeHeight"),
            program.GetUniformLocation("uCloudDensity"),
            program.GetUniformLocation("uVolumeSize"),
            program.GetUniformLocation("uGroundWorldY"),
            program.GetUniformLocation("uFogSlabHeight"),
            program.GetUniformLocation("uHeightFogStrength"),
            program.GetUniformLocation("uShadowTexelSize"),
            program.GetUniformLocation("uShadowTexelSizeNear"),
            program.GetUniformLocation("uShadowTexelSizeMid"),
            program.GetUniformLocation("uShadowMinBias"),
            program.GetUniformLocation("uEnableShadowMap"),
            program.GetUniformLocation("uEnableShadowCascades"),
            program.GetUniformLocation("uCascadeSplitDistance"),
            program.GetUniformLocation("uCascadeMidSplitDistance"),
            program.GetUniformLocation("uCascadeBlendWidth"),
            program.GetUniformLocation("uShadowDistance"),
            program.GetUniformLocation("uShadowFadeStart"),
            program.GetUniformLocation("uEnableCloudAttenuation"));

    private static GodRayUpsampleUniformLocs ResolveGodRayUpsampleUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uHalfResRays"),
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uHistory"),
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uPrevViewProj"),
            program.GetUniformLocation("uHalfResTexelSize"),
            program.GetUniformLocation("uTemporalWeight"),
            program.GetUniformLocation("uHasHistory"));

    private static GodRayCanopyRefineUniformLocs ResolveGodRayCanopyRefineUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uRays"),
            program.GetUniformLocation("uFoliageMask"),
            program.GetUniformLocation("uStrength"));

    private static GodRayCompositeUniformLocs ResolveGodRayCompositeUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uRays"),
            program.GetUniformLocation("uHasCloudMask"),
            program.GetUniformLocation("uCloudMask"),
            program.GetUniformLocation("uCloudPresent"),
            program.GetUniformLocation("uHdrPresent"),
            program.GetUniformLocation("uHdrPaperWhiteNits"),
            program.GetUniformLocation("uHdrPeakNits"),
            program.GetUniformLocation("uTransmittanceComposite"));

    private static VolumeInjectUniformLocs ResolveVolumeInjectUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uCamRight"),
            program.GetUniformLocation("uCamUp"),
            program.GetUniformLocation("uCamForward"),
            program.GetUniformLocation("uLightDir"),
            program.GetUniformLocation("uLightColor"),
            program.GetUniformLocation("uHalfExtent"),
            program.GetUniformLocation("uSliceCount"),
            program.GetUniformLocation("uDepthDistribution"),
            program.GetUniformLocation("uLayerHeight"),
            program.GetUniformLocation("uVolumeHeight"),
            program.GetUniformLocation("uCloudDensity"),
            program.GetUniformLocation("uVolumeSize"),
            program.GetUniformLocation("uGroundWorldY"),
            program.GetUniformLocation("uFogSlabHeight"),
            program.GetUniformLocation("uHeightFogStrength"),
            program.GetUniformLocation("uDebugDensity"),
            program.GetUniformLocation("uLightViewProj"),
            program.GetUniformLocation("uLightViewProjNear"),
            program.GetUniformLocation("uLightViewProjMid"),
            program.GetUniformLocation("uShadowTexelSize"),
            program.GetUniformLocation("uShadowTexelSizeNear"),
            program.GetUniformLocation("uShadowTexelSizeMid"),
            program.GetUniformLocation("uShadowMinBias"),
            program.GetUniformLocation("uEnableShadowMap"),
            program.GetUniformLocation("uEnableShadowCascades"),
            program.GetUniformLocation("uCascadeSplitDistance"),
            program.GetUniformLocation("uCascadeMidSplitDistance"),
            program.GetUniformLocation("uCascadeBlendWidth"),
            program.GetUniformLocation("uShadowDistance"),
            program.GetUniformLocation("uShadowFadeStart"),
            program.GetUniformLocation("uShadowMap"),
            program.GetUniformLocation("uShadowMapNear"),
            program.GetUniformLocation("uShadowMapMid"),
            program.GetUniformLocation("uSliceIndex"),
            program.GetUniformLocation("uCloudGroundTransmittance"),
            program.GetUniformLocation("uHasCloudGroundTransmittance"),
            program.GetUniformLocation("uCloudGroundBasisRight"),
            program.GetUniformLocation("uCloudGroundBasisUp"),
            program.GetUniformLocation("uCloudGroundPlaneCenter"),
            program.GetUniformLocation("uCloudGroundWorldSpan"),
            program.GetUniformLocation("uCloudGroundTexelSize"));

    private static VolumeInjectComputeUniformLocs ResolveVolumeInjectComputeUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uCamRight"),
            program.GetUniformLocation("uCamUp"),
            program.GetUniformLocation("uCamForward"),
            program.GetUniformLocation("uLightDir"),
            program.GetUniformLocation("uLightColor"),
            program.GetUniformLocation("uHalfExtent"),
            program.GetUniformLocation("uFroxelSize"),
            program.GetUniformLocation("uSliceCount"),
            program.GetUniformLocation("uDepthDistribution"),
            program.GetUniformLocation("uLayerHeight"),
            program.GetUniformLocation("uVolumeHeight"),
            program.GetUniformLocation("uCloudDensity"),
            program.GetUniformLocation("uVolumeSize"),
            program.GetUniformLocation("uGroundWorldY"),
            program.GetUniformLocation("uFogSlabHeight"),
            program.GetUniformLocation("uHeightFogStrength"),
            program.GetUniformLocation("uDebugDensity"),
            program.GetUniformLocation("uLightViewProj"),
            program.GetUniformLocation("uLightViewProjNear"),
            program.GetUniformLocation("uLightViewProjMid"),
            program.GetUniformLocation("uShadowTexelSize"),
            program.GetUniformLocation("uShadowTexelSizeNear"),
            program.GetUniformLocation("uShadowTexelSizeMid"),
            program.GetUniformLocation("uShadowMinBias"),
            program.GetUniformLocation("uEnableShadowMap"),
            program.GetUniformLocation("uEnableShadowCascades"),
            program.GetUniformLocation("uCascadeSplitDistance"),
            program.GetUniformLocation("uCascadeMidSplitDistance"),
            program.GetUniformLocation("uCascadeBlendWidth"),
            program.GetUniformLocation("uShadowDistance"),
            program.GetUniformLocation("uShadowFadeStart"),
            program.GetUniformLocation("uShadowMap"),
            program.GetUniformLocation("uShadowMapNear"),
            program.GetUniformLocation("uShadowMapMid"),
            program.GetUniformLocation("uCloudGroundTransmittance"),
            program.GetUniformLocation("uHasCloudGroundTransmittance"),
            program.GetUniformLocation("uCloudGroundBasisRight"),
            program.GetUniformLocation("uCloudGroundBasisUp"),
            program.GetUniformLocation("uCloudGroundPlaneCenter"),
            program.GetUniformLocation("uCloudGroundWorldSpan"),
            program.GetUniformLocation("uCloudGroundTexelSize"));

    private static VolumeIntegrateUniformLocs ResolveVolumeIntegrateUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uFroxelVolume"),
            program.GetUniformLocation("uFroxelOccupancy"),
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uCamRight"),
            program.GetUniformLocation("uCamUp"),
            program.GetUniformLocation("uCamForward"),
            program.GetUniformLocation("uLightDir"),
            program.GetUniformLocation("uLightColor"),
            program.GetUniformLocation("uHalfExtent"),
            program.GetUniformLocation("uSliceCount"),
            program.GetUniformLocation("uFroxelTexelSize"),
            program.GetUniformLocation("uStrength"),
            program.GetUniformLocation("uJitter"),
            program.GetUniformLocation("uScatterGain"),
            program.GetUniformLocation("uExtinction"),
            program.GetUniformLocation("uAmbientFillGain"),
            program.GetUniformLocation("uPhaseDirectivity"),
            program.GetUniformLocation("uDepthDistribution"),
            program.GetUniformLocation("uPrevIntegrate"),
            program.GetUniformLocation("uHasPrevIntegrate"),
            program.GetUniformLocation("uPrevFroxelVolume"),
            program.GetUniformLocation("uHasPrevFroxel"),
            program.GetUniformLocation("uPrevViewProj"),
            program.GetUniformLocation("uPrevCameraPos"),
            program.GetUniformLocation("uPrevCamRight"),
            program.GetUniformLocation("uPrevCamUp"),
            program.GetUniformLocation("uPrevCamForward"),
            program.GetUniformLocation("uPrevHalfExtent"),
            program.GetUniformLocation("uTemporalWeight"),
            program.GetUniformLocation("uFroxelTemporalWeight"),
            program.GetUniformLocation("uCloudTransmittance"),
            program.GetUniformLocation("uCloudData"),
            program.GetUniformLocation("uHasCloudTransmittance"),
            program.GetUniformLocation("uCloudDataDirect"));

    private static CloudUniformLocs ResolveCloudUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uCloudNoise"),
            program.GetUniformLocation("uCoverageMap"),
            program.GetUniformLocation("uSkyViewLut"),
            program.GetUniformLocation("uDetailNoise"),
            program.GetUniformLocation("uCloudStbn"),
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uGroundWorldY"),
            program.GetUniformLocation("uPlanetRadius"),
            program.GetUniformLocation("uSunDir"),
            program.GetUniformLocation("uSunIntensity"),
            program.GetUniformLocation("uLayerHeight"),
            program.GetUniformLocation("uVolumeHeight"),
            program.GetUniformLocation("uDensity"),
            program.GetUniformLocation("uCoverageScale"),
            program.GetUniformLocation("uVolumeSize"),
            program.GetUniformLocation("uPixelAngularSize"),
            program.GetUniformLocation("uWindOffset"),
            program.GetUniformLocation("uCirrusStrength"),
            program.GetUniformLocation("uCirrusWindOffset"),
            program.GetUniformLocation("uCirrusWindDir"),
            program.GetUniformLocation("uQuality"),
            program.GetUniformLocation("uMarchSteps"),
            program.GetUniformLocation("uDebugView"),
            program.GetUniformLocation("uHasSceneDepth"),
            program.GetUniformLocation("uFramePhase"),
            program.GetUniformLocation("uCloudFrameIndex"),
            program.GetUniformLocation("uHasCloudNoise"),
            program.GetUniformLocation("uHasDetailNoise"),
            program.GetUniformLocation("uHasCloudStbn"),
            program.GetUniformLocation("uHasCoverageMap"),
            program.GetUniformLocation("uHasSkyLut"),
            program.GetUniformLocation("uCloudDataDirect"),
            program.GetUniformLocation("uDensityAssetVersion"),
            program.GetUniformLocation("uDensityAssetProfileCode"),
            program.GetUniformLocation("uSparseCloudAtlas"),
            program.GetUniformLocation("uSparseCloudPageL0"),
            program.GetUniformLocation("uSparseCloudPageL1"),
            program.GetUniformLocation("uSparseCloudPageL2"),
            program.GetUniformLocation("uSparseCloudOriginL0"),
            program.GetUniformLocation("uSparseCloudOriginL1"),
            program.GetUniformLocation("uSparseCloudOriginL2"),
            program.GetUniformLocation("uHasSparseCloudTraversal"),
            program.GetUniformLocation("uCloudLightNear"),
            program.GetUniformLocation("uCloudLightFar"),
            program.GetUniformLocation("uCloudLightBasisRight"),
            program.GetUniformLocation("uCloudLightBasisUp"),
            program.GetUniformLocation("uCloudLightBasisForward"),
            program.GetUniformLocation("uCloudLightNearPlaneCenter"),
            program.GetUniformLocation("uCloudLightFarPlaneCenter"),
            program.GetUniformLocation("uCloudLightNearWorldSpan"),
            program.GetUniformLocation("uCloudLightFarWorldSpan"),
            program.GetUniformLocation("uCloudLightNearDepthMin"),
            program.GetUniformLocation("uCloudLightFarDepthMin"),
            program.GetUniformLocation("uCloudLightNearDepthSpan"),
            program.GetUniformLocation("uCloudLightFarDepthSpan"),
            program.GetUniformLocation("uCloudLightNearDepth"),
            program.GetUniformLocation("uCloudLightFarDepth"),
            program.GetUniformLocation("uCloudLightNearOverlap"),
            program.GetUniformLocation("uHasCloudLightNear"),
            program.GetUniformLocation("uHasCloudLightFar"),
            program.GetUniformLocation("uCloudScatterOctave1"),
            program.GetUniformLocation("uCloudScatterOctave2"),
            program.GetUniformLocation("uCloudScatterEnergyClamp"),
            program.GetUniformLocation("uCloudCachedSkyVisibilityFloor"),
            program.GetUniformLocation("uCloudGroundBounceColor"),
            program.GetUniformLocation("uCloudGroundBounceStrength"),
            program.GetUniformLocation("uCloudLocalConeTapCount"),
            program.GetUniformLocation("uCloudLocalConeRange"),
            program.GetUniformLocation("uCloudLocalConeOpticalDepthScale"),
            program.GetUniformLocation("uCumulusLayerCount"),
            program.GetUniformLocation("uInterDeckGap"),
            program.GetUniformLocation("uHeightVariance"),
            program.GetUniformLocation("uUpperThicknessScale"),
            program.GetUniformLocation("uUpperCoverageScale"),
            program.GetUniformLocation("uUpperDensityScale"),
            program.GetUniformLocation("uUpperWindOffset"),
            program.GetUniformLocation("uCirrusGap"),
            program.GetUniformLocation("uCirrusThickness"),
            program.GetUniformLocation("uStyleBias"));

    private static CloudTemporalUniformLocs ResolveCloudTemporalUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uCurrentClouds"),
            program.GetUniformLocation("uCurrentCloudData"),
            program.GetUniformLocation("uHistoryClouds"),
            program.GetUniformLocation("uHistoryCloudData"),
            program.GetUniformLocation("uHistoryCloudMoments"),
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uPrevViewProj"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uPrevCameraPos"),
            program.GetUniformLocation("uWindDelta"),
            program.GetUniformLocation("uCirrusWindDelta"),
            program.GetUniformLocation("uTexelSize"),
            program.GetUniformLocation("uTemporalWeight"),
            program.GetUniformLocation("uMomentSigma"),
            program.GetUniformLocation("uMomentMinBand"),
            program.GetUniformLocation("uHistoryConfidence"),
            program.GetUniformLocation("uTemporalStability"),
            program.GetUniformLocation("uHasHistory"),
            program.GetUniformLocation("uHasMoments"),
            program.GetUniformLocation("uCloudDataDirect"));

    private static CloudUpsampleUniformLocs ResolveCloudUpsampleUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uClouds"),
            program.GetUniformLocation("uCloudData"),
            program.GetUniformLocation("uCloudTexelSize"),
            program.GetUniformLocation("uHasSceneDepth"),
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uSunDir"),
            program.GetUniformLocation("uSunCosDiscEdge"),
            program.GetUniformLocation("uSunDiscVisibility"),
            program.GetUniformLocation("uCloudDataDirect"),
            program.GetUniformLocation("uCloudExposure"),
            program.GetUniformLocation("uHdrPresent"),
            program.GetUniformLocation("uHdrPaperWhiteNits"),
            program.GetUniformLocation("uHdrPeakNits"),
            program.GetUniformLocation("uApplyCloudEncoding"),
            program.GetUniformLocation("uCloudSourceFullResolution"));

    private static CloudRepairUniformLocs ResolveCloudRepairUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uClouds"),
            program.GetUniformLocation("uCloudData"),
            program.GetUniformLocation("uSceneDepth"),
            program.GetUniformLocation("uCloudNoise"),
            program.GetUniformLocation("uDetailNoise"),
            program.GetUniformLocation("uCloudStbn"),
            program.GetUniformLocation("uCoverageMap"),
            program.GetUniformLocation("uSkyViewLut"),
            program.GetUniformLocation("uCloudTexelSize"),
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uSunDir"),
            program.GetUniformLocation("uSunIntensity"),
            program.GetUniformLocation("uGroundWorldY"),
            program.GetUniformLocation("uPlanetRadius"),
            program.GetUniformLocation("uLayerHeight"),
            program.GetUniformLocation("uVolumeHeight"),
            program.GetUniformLocation("uDensity"),
            program.GetUniformLocation("uCoverageScale"),
            program.GetUniformLocation("uVolumeSize"),
            program.GetUniformLocation("uPixelAngularSize"),
            program.GetUniformLocation("uWindOffset"),
            program.GetUniformLocation("uCirrusStrength"),
            program.GetUniformLocation("uCirrusWindOffset"),
            program.GetUniformLocation("uCirrusWindDir"),
            program.GetUniformLocation("uMarchSteps"),
            program.GetUniformLocation("uHasSceneDepth"),
            program.GetUniformLocation("uHasCloudNoise"),
            program.GetUniformLocation("uHasDetailNoise"),
            program.GetUniformLocation("uHasCloudStbn"),
            program.GetUniformLocation("uHasCoverageMap"),
            program.GetUniformLocation("uHasSkyLut"),
            program.GetUniformLocation("uSourceCloudDataDirect"),
            program.GetUniformLocation("uDensityAssetVersion"),
            program.GetUniformLocation("uCloudFrameIndex"),
            program.GetUniformLocation("uRepairStability"),
            program.GetUniformLocation("uSparseCloudAtlas"),
            program.GetUniformLocation("uSparseCloudPageL0"),
            program.GetUniformLocation("uSparseCloudPageL1"),
            program.GetUniformLocation("uSparseCloudPageL2"),
            program.GetUniformLocation("uSparseCloudOriginL0"),
            program.GetUniformLocation("uSparseCloudOriginL1"),
            program.GetUniformLocation("uSparseCloudOriginL2"),
            program.GetUniformLocation("uHasSparseCloudTraversal"),
            program.GetUniformLocation("uCumulusLayerCount"),
            program.GetUniformLocation("uInterDeckGap"),
            program.GetUniformLocation("uHeightVariance"),
            program.GetUniformLocation("uUpperThicknessScale"),
            program.GetUniformLocation("uUpperCoverageScale"),
            program.GetUniformLocation("uUpperDensityScale"),
            program.GetUniformLocation("uUpperWindOffset"),
            program.GetUniformLocation("uCirrusGap"),
            program.GetUniformLocation("uCirrusThickness"),
            program.GetUniformLocation("uStyleBias"));

    private static CloudCompositeUniformLocs ResolveCloudCompositeUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uRays"),
            program.GetUniformLocation("uCloudPresent"),
            program.GetUniformLocation("uCloudExposure"),
            program.GetUniformLocation("uHdrPresent"),
            program.GetUniformLocation("uHdrPaperWhiteNits"),
            program.GetUniformLocation("uHdrPeakNits"),
            program.GetUniformLocation("uApplyCloudEncoding"));

    private static AtmoTransUniformLocs ResolveAtmoTransUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uTurbidity"),
            program.GetUniformLocation("uHorizonFalloff"));

    private static AtmoSkyViewUniformLocs ResolveAtmoSkyViewUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uTransmittanceLut"),
            program.GetUniformLocation("uSunDir"),
            program.GetUniformLocation("uTurbidity"),
            program.GetUniformLocation("uSunIntensity"),
            program.GetUniformLocation("uHorizonFalloff"));

    private static AtmoSkyUniformLocs ResolveAtmoSkyUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uSkyViewLut"),
            program.GetUniformLocation("uTurbidity"),
            program.GetUniformLocation("uHorizonFalloff"),
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uLightDir"),
            program.GetUniformLocation("uSunIntensity"),
            program.GetUniformLocation("uHorizonFogStrength"),
            program.GetUniformLocation("uGroundWorldY"),
            program.GetUniformLocation("uSkyExposure"),
            program.GetUniformLocation("uSunDiscStrength"),
            program.GetUniformLocation("uSunDiscBrightness"),
            program.GetUniformLocation("uSunCosDiscEdge"),
            program.GetUniformLocation("uMoonCosDiscEdge"),
            program.GetUniformLocation("uRenderTime"),
            program.GetUniformLocation("uViewportAspect"),
            program.GetUniformLocation("uSunDiscRadiusUv"),
            program.GetUniformLocation("uHdrPresent"));

    private static ProceduralSkyUniformLocs ResolveProceduralSkyUniformLocs(GlProceduralSkyProgram program) =>
        new(
            program.GetUniformLocation("uInvViewProj"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uLightDir"),
            program.GetUniformLocation("uSunIntensity"),
            program.GetUniformLocation("uSkyExposure"),
            program.GetUniformLocation("uRenderTime"),
            program.GetUniformLocation("uTurbidity"),
            program.GetUniformLocation("uHorizonFalloff"),
            program.GetUniformLocation("uHorizonFogStrength"),
            program.GetUniformLocation("uGroundWorldY"),
            program.GetUniformLocation("uSunDiscStrength"),
            program.GetUniformLocation("uSunDiscBrightness"),
            program.GetUniformLocation("uSunCosDiscEdge"),
            program.GetUniformLocation("uMoonCosDiscEdge"),
            program.GetUniformLocation("uViewportAspect"),
            program.GetUniformLocation("uSunDiscRadiusUv"),
            program.GetUniformLocation("uSunElevation"),
            program.GetUniformLocation("uHdrPresent"));
}
