namespace AutoPBR.App.Rendering.OpenGL;

/// <summary>OpenGL implementation of <see cref="IRenderPreviewBackend"/>; GPU entry points must run on the OpenGL thread (Avalonia <see cref="AutoPBR.App.Controls.GlPbrPreviewControl"/> callbacks).</summary>
public sealed partial class OpenGlPreviewBackend
{
    private readonly record struct MainProgramUniformLocs(
        int TaaCurrViewProj,
        int PrevViewProj,
        int View,
        int Proj,
        int LightViewProj,
        int Model,
        int PrevModel,
        int CameraPos,
        int LightDir,
        int LightColor,
        int SkyTint,
        int GroundTint,
        int PreviewLayerDebugTint,
        int ShadowTexelSize,
        int TextureAtlasScale,
        int Ambient,
        int NormalStrength,
        int HeightStrength,
        int SpecularStrength,
        int RoughnessScale,
        int Exposure,
        int HdrPresent,
        int ParallaxAoStrength,
        int ParallaxShadowSoftness,
        int ParallaxMaxUvShift,
        int ParallaxUvScale,
        int ParallaxHeightTexSize,
        int TessellationLevel,
        int TessellationDisplacementStrength,
        int AlphaCutoff,
        int SssStrength,
        int IblStrength,
        int EmissionStrength,
        int AtmosphereSunIntensity,
        int ShadowMinBias,
        int ShadowMaxBias,
        int ShadowSoftnessTexels,
        int ParallaxTraceLayers,
        int ParallaxRefineSteps,
        int ParallaxShadowSamples,
        int EnableTessellationDisplacement,
        int EnableParallax,
        int EnableParallaxAo,
        int EnableNormalMap,
        int EnableSpecularMap,
        int SceneKind,
        int IsGroundPass,
        int ItemAlphaBlend,
        int EntityAlphaMode,
        int PreviewDepthLayerDebug,
        int EnableSss,
        int EnableParallaxShadow,
        int EnableIbl,
        int EnableAtmosphericSky,
        int AerialFogStrength,
        int TerrainFogStart,
        int TerrainFogEnd,
        int TerrainPomFadeStart,
        int TerrainPomFadeEnd,
        int EnableShadowMap,
        int HasNormal,
        int HasSpecular,
        int HasHeight,
        int Albedo,
        int Normal,
        int Specular,
        int Height,
        int AlbedoArray,
        int NormalArray,
        int SpecularArray,
        int HeightArray,
        int ShadowMap,
        int ShadowMapNear,
        int ShadowMapMid,
        int LightViewProjNear,
        int LightViewProjMid,
        int EnableShadowCascades,
        int CascadeSplitDistance,
        int CascadeMidSplitDistance,
        int CascadeBlendWidth,
        int ShadowDistance,
        int ShadowFadeStart,
        int ShadowTexelSizeNear,
        int ShadowTexelSizeMid,
        int AtmoSkyViewLut,
        int GenesisUseMaterialDrawRecord,
        int GenesisUseMaterialTextureArray,
        int GenesisDrawRecordIndex);

    private readonly record struct ShadowProgramUniformLocs(
        int LightViewProj,
        int Model,
        int SceneKind,
        int EntityAlphaMode,
        int ItemAlphaBlend,
        int Albedo,
        int AlbedoArray,
        int AlphaCutoff,
        int GenesisUseMaterialDrawRecord,
        int GenesisUseMaterialTextureArray,
        int GenesisDrawRecordIndex);

    private readonly record struct LineProgramUniformLocs(int Mvp);

    private readonly record struct MoonProgramUniformLocs(
        int ViewProj,
        int MoonCenter,
        int MoonRight,
        int MoonUp,
        int MoonFacing,
        int CameraPos,
        int Radius,
        int MoonCosDiscEdge,
        int DiscStrength,
        int GlowStrength,
        int TextureSharpness,
        int MoonAlbedo);

    private MainProgramUniformLocs _mainUniformLocs;
    private ShadowProgramUniformLocs _shadowUniformLocs;
    private LineProgramUniformLocs _lineUniformLocs;
    private MoonProgramUniformLocs _moonUniformLocs;

    private static MainProgramUniformLocs ResolveMainProgramUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uTaaCurrViewProj"),
            program.GetUniformLocation("uPrevViewProj"),
            program.GetUniformLocation("uView"),
            program.GetUniformLocation("uProj"),
            program.GetUniformLocation("uLightViewProj"),
            program.GetUniformLocation("uModel"),
            program.GetUniformLocation("uPrevModel"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uLightDir"),
            program.GetUniformLocation("uLightColor"),
            program.GetUniformLocation("uSkyTint"),
            program.GetUniformLocation("uGroundTint"),
            program.GetUniformLocation("uPreviewLayerDebugTint"),
            program.GetUniformLocation("uShadowTexelSize"),
            program.GetUniformLocation("uTextureAtlasScale"),
            program.GetUniformLocation("uAmbient"),
            program.GetUniformLocation("uNormalStrength"),
            program.GetUniformLocation("uHeightStrength"),
            program.GetUniformLocation("uSpecularStrength"),
            program.GetUniformLocation("uRoughnessScale"),
            program.GetUniformLocation("uExposure"),
            program.GetUniformLocation("uHdrPresent"),
            program.GetUniformLocation("uParallaxAoStrength"),
            program.GetUniformLocation("uParallaxShadowSoftness"),
            program.GetUniformLocation("uParallaxMaxUvShift"),
            program.GetUniformLocation("uParallaxUvScale"),
            program.GetUniformLocation("uParallaxHeightTexSize"),
            program.GetUniformLocation("uTessellationLevel"),
            program.GetUniformLocation("uTessellationDisplacementStrength"),
            program.GetUniformLocation("uAlphaCutoff"),
            program.GetUniformLocation("uSssStrength"),
            program.GetUniformLocation("uIblStrength"),
            program.GetUniformLocation("uEmissionStrength"),
            program.GetUniformLocation("uAtmosphereSunIntensity"),
            program.GetUniformLocation("uShadowMinBias"),
            program.GetUniformLocation("uShadowMaxBias"),
            program.GetUniformLocation("uShadowSoftnessTexels"),
            program.GetUniformLocation("uParallaxTraceLayers"),
            program.GetUniformLocation("uParallaxRefineSteps"),
            program.GetUniformLocation("uParallaxShadowSamples"),
            program.GetUniformLocation("uEnableTessellationDisplacement"),
            program.GetUniformLocation("uEnableParallax"),
            program.GetUniformLocation("uEnableParallaxAo"),
            program.GetUniformLocation("uEnableNormalMap"),
            program.GetUniformLocation("uEnableSpecularMap"),
            program.GetUniformLocation("uSceneKind"),
            program.GetUniformLocation("uIsGroundPass"),
            program.GetUniformLocation("uItemAlphaBlend"),
            program.GetUniformLocation("uEntityAlphaMode"),
            program.GetUniformLocation("uPreviewDepthLayerDebug"),
            program.GetUniformLocation("uEnableSss"),
            program.GetUniformLocation("uEnableParallaxShadow"),
            program.GetUniformLocation("uEnableIbl"),
            program.GetUniformLocation("uEnableAtmosphericSky"),
            program.GetUniformLocation("uAerialFogStrength"),
            program.GetUniformLocation("uTerrainFogStart"),
            program.GetUniformLocation("uTerrainFogEnd"),
            program.GetUniformLocation("uTerrainPomFadeStart"),
            program.GetUniformLocation("uTerrainPomFadeEnd"),
            program.GetUniformLocation("uEnableShadowMap"),
            program.GetUniformLocation("uHasNormal"),
            program.GetUniformLocation("uHasSpecular"),
            program.GetUniformLocation("uHasHeight"),
            program.GetUniformLocation("uAlbedo"),
            program.GetUniformLocation("uNormal"),
            program.GetUniformLocation("uSpecular"),
            program.GetUniformLocation("uHeight"),
            program.GetUniformLocation("uAlbedoArray"),
            program.GetUniformLocation("uNormalArray"),
            program.GetUniformLocation("uSpecularArray"),
            program.GetUniformLocation("uHeightArray"),
            program.GetUniformLocation("uShadowMap"),
            program.GetUniformLocation("uShadowMapNear"),
            program.GetUniformLocation("uShadowMapMid"),
            program.GetUniformLocation("uLightViewProjNear"),
            program.GetUniformLocation("uLightViewProjMid"),
            program.GetUniformLocation("uEnableShadowCascades"),
            program.GetUniformLocation("uCascadeSplitDistance"),
            program.GetUniformLocation("uCascadeMidSplitDistance"),
            program.GetUniformLocation("uCascadeBlendWidth"),
            program.GetUniformLocation("uShadowDistance"),
            program.GetUniformLocation("uShadowFadeStart"),
            program.GetUniformLocation("uShadowTexelSizeNear"),
            program.GetUniformLocation("uShadowTexelSizeMid"),
            program.GetUniformLocation("uAtmoSkyViewLut"),
            program.GetUniformLocation("uGenesisUseMaterialDrawRecord"),
            program.GetUniformLocation("uGenesisUseMaterialTextureArray"),
            program.GetUniformLocation("uGenesisDrawRecordIndex"));

    private static ShadowProgramUniformLocs ResolveShadowProgramUniformLocs(GlShaderProgram program) =>
        new(
            program.GetUniformLocation("uLightViewProj"),
            program.GetUniformLocation("uModel"),
            program.GetUniformLocation("uSceneKind"),
            program.GetUniformLocation("uEntityAlphaMode"),
            program.GetUniformLocation("uItemAlphaBlend"),
            program.GetUniformLocation("uAlbedo"),
            program.GetUniformLocation("uAlbedoArray"),
            program.GetUniformLocation("uAlphaCutoff"),
            program.GetUniformLocation("uGenesisUseMaterialDrawRecord"),
            program.GetUniformLocation("uGenesisUseMaterialTextureArray"),
            program.GetUniformLocation("uGenesisDrawRecordIndex"));

    private static LineProgramUniformLocs ResolveLineProgramUniformLocs(GlLineShaderProgram program) =>
        new(program.GetUniformLocation("uMvp"));

    private static MoonProgramUniformLocs ResolveMoonProgramUniformLocs(GlMoonBillboardProgram program) =>
        new(
            program.GetUniformLocation("uViewProj"),
            program.GetUniformLocation("uMoonCenter"),
            program.GetUniformLocation("uMoonRight"),
            program.GetUniformLocation("uMoonUp"),
            program.GetUniformLocation("uMoonFacing"),
            program.GetUniformLocation("uCameraPos"),
            program.GetUniformLocation("uRadius"),
            program.GetUniformLocation("uMoonCosDiscEdge"),
            program.GetUniformLocation("uDiscStrength"),
            program.GetUniformLocation("uGlowStrength"),
            program.GetUniformLocation("uTextureSharpness"),
            program.GetUniformLocation("uMoonAlbedo"));
}
