namespace AutoPBR.Core;

public static class AutoPbrDefaults
{
    public const float DefaultNormalIntensity = 1f;
    public const float DefaultHeightIntensity = 0.12f;
    public const float DefaultHeightBrightness = 1f;
    public const float DefaultSmoothnessScale = 1f;
    public const float DefaultMetallicBoost = 1f;
    public const int DefaultPorosityBias = 0;

    // Matches upstream Python `excluded_names` list (by filename).
    public static readonly HashSet<string> ExcludedFileNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "blast_furnace_front_on.png",
        "campfire_fire.png",
        "campfire_log_lit.png",
        "chain_command_block_back.png",
        "chain_command_block_conditional.png",
        "chain_command_block_front.png",
        "chain_command_block_side.png",
        "command_block_back.png",
        "command_block_conditional.png",
        "command_block_front.png",
        "command_block_side.png",
        "crimson_stem.png",
        "fire_0.png",
        "fire_1.png",
        "kelp.png",
        "kelp_plant.png",
        "lava_flow.png",
        "lava_still.png",
        "nether_portal.png",
        "pumpkin_face_on.png",
        "redstone_lamp_on.png",
        "repeating_command_block_back.png",
        "repeating_command_block_conditional.png",
        "repeating_command_block_front.png",
        "repeating_command_block_side.png",
        "respawn_anchor_top.png",
        "seagrass.png",
        "smoker_front_on.png",
        "soul_campfire_fire.png",
        "soul_campfire_log_lit.png",
        "soul_fire_0.png",
        "soul_fire_1.png",
        "stonecutter_saw.png",
        "tall_seagrass_bottom.png",
        "tall_seagrass_top.png",
        "warped_stem.png",
        "water_flow.png",
        "water_still.png",
    };

    // Relative keys for plant textures (namespace-prefixed: \minecraft\block\foo).
    public static readonly IReadOnlyList<string> PlantTextureKeys =
    [
        "\\minecraft\\block\\acacia_sapling",
        "\\minecraft\\block\\birch_sapling",
        "\\minecraft\\block\\dark_oak_sapling",
        "\\minecraft\\block\\jungle_sapling",
        "\\minecraft\\block\\oak_sapling",
        "\\minecraft\\block\\spruce_sapling",
        "\\minecraft\\block\\allium",
        "\\minecraft\\block\\azure_bluet",
        "\\minecraft\\block\\blue_orchid",
        "\\minecraft\\block\\cornflower",
        "\\minecraft\\block\\dandelion",
        "\\minecraft\\block\\lilac_top",
        "\\minecraft\\block\\lilac_bottom",
        "\\minecraft\\block\\lily_of_the_valley",
        "\\minecraft\\block\\orange_tulip",
        "\\minecraft\\block\\oxeye_daisy",
        "\\minecraft\\block\\peony_top",
        "\\minecraft\\block\\peony_bottom",
        "\\minecraft\\block\\pink_tulip",
        "\\minecraft\\block\\poppy",
        "\\minecraft\\block\\red_tulip",
        "\\minecraft\\block\\rose_bush_top",
        "\\minecraft\\block\\rose_bush_bottom",
        "\\minecraft\\block\\sunflower_back",
        "\\minecraft\\block\\sunflower_front",
        "\\minecraft\\block\\sunflower_bottom",
        "\\minecraft\\block\\sunflower_top",
        "\\minecraft\\block\\white_tulip",
        "\\minecraft\\block\\wither_rose",
        "\\minecraft\\block\\brown_mushroom",
        "\\minecraft\\block\\red_mushroom",
        "\\minecraft\\block\\hanging_roots",
        "\\minecraft\\block\\spore_blossom",
        "\\minecraft\\block\\small_dripleaf_top_extra",
        "\\minecraft\\block\\small_dripleaf_top",
        "\\minecraft\\block\\small_dripleaf_stem_top",
        "\\minecraft\\block\\small_dripleaf_stem_bottom",
        "\\minecraft\\block\\big_dripleaf_stem",
        "\\minecraft\\block\\big_dripleaf_tip",
        "\\minecraft\\block\\big_dripleaf_top",
        "\\minecraft\\block\\big_dripleaf_tip_extra",
        "\\minecraft\\block\\big_dripleaf_top_extra",
        "\\minecraft\\block\\dead_bush",
        "\\minecraft\\block\\fern",
        "\\minecraft\\block\\large_fern_bottom",
        "\\minecraft\\block\\large_fern_top",
        "\\minecraft\\block\\short_grass",
        "\\minecraft\\block\\tall_grass_bottom",
        "\\minecraft\\block\\tall_grass_top",
        "\\minecraft\\block\\tall_seagrass_bottom",
        "\\minecraft\\block\\tall_seagrass_top",
        "\\minecraft\\block\\beetroots_stage0",
        "\\minecraft\\block\\beetroots_stage1",
        "\\minecraft\\block\\beetroots_stage2",
        "\\minecraft\\block\\beetroots_stage3",
        "\\minecraft\\block\\carrots_stage0",
        "\\minecraft\\block\\carrots_stage1",
        "\\minecraft\\block\\carrots_stage2",
        "\\minecraft\\block\\carrots_stage3",
        "\\minecraft\\block\\potatoes_stage0",
        "\\minecraft\\block\\potatoes_stage1",
        "\\minecraft\\block\\potatoes_stage2",
        "\\minecraft\\block\\potatoes_stage3",
        "\\minecraft\\block\\wheat",
        "\\minecraft\\block\\sweet_berries",
        "\\minecraft\\block\\nether_wart_stage0",
        "\\minecraft\\block\\nether_wart_stage1",
        "\\minecraft\\block\\nether_wart_stage2",
        "\\minecraft\\block\\cocoa_stage0",
        "\\minecraft\\block\\cocoa_stage1",
        "\\minecraft\\block\\cocoa_stage2",
    ];
}
