namespace AutoPBR.Core;

public static class AutoPbrDefaults
{
    public const float DefaultNormalIntensity = 1f;
    public const float DefaultHeightIntensity = 0.12f;
    public const float DefaultHeightBrightness = 1f;

    // Matches upstream Python `excluded_names` list (by filename).
    public static readonly HashSet<string> ExcludedFileNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "blast_furnace_front_on.png",
        "campfire_fire.png",
        "campfire_log_lit.png",
        "chain_command_block_back.png",
        "chain_command_block_conditional.png",
        "chain_command_block_front.png",
        "chain_command_block_side.png",
        "command_block_back.png",
        "command_block_conditional.png",
        "command_block_front.png",
        "command_block_side.png",
        "crimson_stem.png",
        "fire_0.png",
        "fire_1.png",
        "kelp.png",
        "kelp_plant.png",
        "lava_flow.png",
        "lava_still.png",
        "nether_portal.png",
        "pumpkin_face_on.png",
        "redstone_lamp_on.png",
        "repeating_command_block_back.png",
        "repeating_command_block_conditional.png",
        "repeating_command_block_front.png",
        "repeating_command_block_side.png",
        "respawn_anchor_top.png",
        "seagrass.png",
        "smoker_front_on.png",
        "soul_campfire_fire.png",
        "soul_campfire_log_lit.png",
        "soul_fire_0.png",
        "soul_fire_1.png",
        "stonecutter_saw.png",
        "tall_seagrass_bottom.png",
        "tall_seagrass_top.png",
        "warped_stem.png",
        "water_flow.png",
        "water_still.png",
    };

    // Matches upstream Python `plant_blocks` list (relative keys like "\block\foo").
    public static readonly IReadOnlyList<string> PlantTextureKeys =
    [
        "\\block/acacia_sapling",
        "\\block/birch_sapling",
        "\\block/dark_oak_sapling",
        "\\block/jungle_sapling",
        "\\block/oak_sapling",
        "\\block/spruce_sapling",
        "\\block/allium",
        "\\block/azure_bluet",
        "\\block/blue_orchid",
        "\\block/cornflower",
        "\\block/dandelion",
        "\\block/lilac_top",
        "\\block/lilac_bottom",
        "\\block/lily_of_the_valley",
        "\\block/orange_tulip",
        "\\block/oxeye_daisy",
        "\\block/peony_top",
        "\\block/peony_bottom",
        "\\block/pink_tulip",
        "\\block/poppy",
        "\\block/red_tulip",
        "\\block/rose_bush_top",
        "\\block/rose_bush_bottom",
        "\\block/sunflower_back",
        "\\block/sunflower_front",
        "\\block/sunflower_bottom",
        "\\block/sunflower_top",
        "\\block/white_tulip",
        "\\block/wither_rose",
        "\\block/brown_mushroom",
        "\\block/red_mushroom",
        "\\block/hanging_roots",
        "\\block/spore_blossom",
        "\\block/small_dripleaf_top_extra",
        "\\block/small_dripleaf_top",
        "\\block/small_dripleaf_stem_top",
        "\\block/small_dripleaf_stem_bottom",
        "\\block/big_dripleaf_stem",
        "\\block/big_dripleaf_tip",
        "\\block/big_dripleaf_top",
        "\\block/big_dripleaf_tip_extra",
        "\\block/big_dripleaf_top_extra",
        "\\block/dead_bush",
        "\\block/fern",
        "\\block/large_fern_bottom",
        "\\block/large_fern_top",
        "\\block/short_grass",
        "\\block/tall_grass_bottom",
        "\\block/tall_grass_top",
        "\\block/tall_seagrass_bottom",
        "\\block/tall_seagrass_top",
        "\\block/beetroots_stage0",
        "\\block/beetroots_stage1",
        "\\block/beetroots_stage2",
        "\\block/beetroots_stage3",
        "\\block/carrots_stage0",
        "\\block/carrots_stage1",
        "\\block/carrots_stage2",
        "\\block/carrots_stage3",
        "\\block/potatoes_stage0",
        "\\block/potatoes_stage1",
        "\\block/potatoes_stage2",
        "\\block/potatoes_stage3",
        "\\block/wheat",
        "\\block/sweet_berries",
        "\\block/nether_wart_stage0",
        "\\block/nether_wart_stage1",
        "\\block/nether_wart_stage2",
        "\\block/cocoa_stage0",
        "\\block/cocoa_stage1",
        "\\block/cocoa_stage2",
    ];
}
